import {
  type Database,
  documents,
  issues,
  notifications,
  projects,
  users,
  workspaceMembers,
  workspaces,
} from '@relay/database';
import type { NudgeKind } from '@relay/shared';
import { and, count, eq, sql } from 'drizzle-orm';

/**
 * Engagement nudges.
 *
 * Prompts that push someone toward the next useful thing: create a workspace,
 * add a project, try a document, invite a teammate. Generated by a periodic
 * scan rather than triggered by an event, because the interesting signal is an
 * *absence* -- nothing happened -- and absences do not fire events.
 *
 * Two rules keep this from becoming spam, which is the only thing that matters
 * about a feature like this:
 *
 * - **One nudge per user per scan.** Someone with an empty account trips
 *   several rules at once; sending all of them is how an inbox gets ignored.
 *   Rules are ordered, and the first match wins.
 * - **A weekly bucket in the dedupe key.** The same nudge cannot arrive twice
 *   in one week, and re-running the scan job is a no-op rather than a repeat.
 */

export type Nudge = {
  /** Constrained to the shared list, so every nudge has a guide to open. */
  kind: NudgeKind;
  title: string;
  body: string;
  workspaceId: string | null;
};

/** ISO week bucket, so a nudge recurs at most weekly. */
export function weekBucket(now: Date = new Date()): string {
  const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  // Thursday of the current week determines the ISO year.
  date.setUTCDate(date.getUTCDate() + 4 - (date.getUTCDay() || 7));

  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((date.getTime() - yearStart.getTime()) / 86_400_000 + 1) / 7);

  return `${date.getUTCFullYear()}-W${String(week).padStart(2, '0')}`;
}

export function dedupeKeyFor(nudge: Nudge, now: Date = new Date()): string {
  return `nudge:${nudge.kind}:${nudge.workspaceId ?? 'global'}:${weekBucket(now)}`;
}

/**
 * Decide the single most useful nudge for one user, or none.
 *
 * Ordered by how early the user is in the funnel: there is no point suggesting
 * they invite a teammate to a workspace that has no work in it yet.
 */
export async function nudgeFor(db: Database, userId: string): Promise<Nudge | null> {
  const memberships = await db
    .select({ workspaceId: workspaceMembers.workspaceId, name: workspaces.name })
    .from(workspaceMembers)
    .innerJoin(workspaces, eq(workspaces.id, workspaceMembers.workspaceId))
    .where(eq(workspaceMembers.userId, userId));

  if (memberships.length === 0) {
    return {
      kind: 'create_workspace',
      title: 'Create your first workspace',
      body: 'Workspaces hold your projects, issues and documents. Start with one.',
      workspaceId: null,
    };
  }

  // Look at the workspace they joined first; it is the one most likely theirs.
  const workspace = memberships[0]!;
  const { workspaceId } = workspace;

  const [projectCount] = await db
    .select({ n: count() })
    .from(projects)
    .where(eq(projects.workspaceId, workspaceId));

  if ((projectCount?.n ?? 0) === 0) {
    return {
      kind: 'create_project',
      title: `Add a project to ${workspace.name}`,
      body: 'Projects group issues and give them readable keys like REL-1.',
      workspaceId,
    };
  }

  const [issueCount] = await db
    .select({ n: count() })
    .from(issues)
    .where(eq(issues.workspaceId, workspaceId));

  if ((issueCount?.n ?? 0) === 0) {
    return {
      kind: 'create_issue',
      title: 'Track your first issue',
      body: 'Add something to the board and drag it through to done.',
      workspaceId,
    };
  }

  const [documentCount] = await db
    .select({ n: count() })
    .from(documents)
    .where(eq(documents.workspaceId, workspaceId));

  if ((documentCount?.n ?? 0) === 0) {
    return {
      kind: 'try_document',
      title: 'Try a collaborative document',
      body: 'Open one in two windows and type in both. Edits merge instead of overwriting.',
      workspaceId,
    };
  }

  const [memberCount] = await db
    .select({ n: count() })
    .from(workspaceMembers)
    .where(eq(workspaceMembers.workspaceId, workspaceId));

  if ((memberCount?.n ?? 0) <= 1) {
    return {
      kind: 'invite_teammate',
      title: 'Invite someone to your workspace',
      body: 'Presence, mentions and live editing need a second person to be worth much.',
      workspaceId,
    };
  }

  const [stale] = await db
    .select({ n: count() })
    .from(issues)
    .where(
      and(
        eq(issues.workspaceId, workspaceId),
        eq(issues.status, 'IN_PROGRESS'),
        sql`${issues.updatedAt} < now() - interval '7 days'`,
      ),
    );

  if ((stale?.n ?? 0) > 0) {
    return {
      kind: 'stale_issues',
      title: `${stale!.n} issue${stale!.n === 1 ? '' : 's'} stuck in progress`,
      body: 'Nothing has moved on these for a week. Worth a look?',
      workspaceId,
    };
  }

  return null;
}

/**
 * Deliver a nudge, unless one just like it already went out this week.
 *
 * The insert relies on the unique index over `(user_id, dedupe_key)` rather
 * than a read-then-write check, so two concurrent scans cannot both decide the
 * nudge is missing and send it.
 */
export async function deliverNudge(
  db: Database,
  userId: string,
  nudge: Nudge,
  now: Date = new Date(),
): Promise<boolean> {
  // A nudge with no workspace still needs one for the row; use the user's own
  // id as the entity so the column stays meaningful.
  const inserted = await db
    .insert(notifications)
    .values({
      workspaceId: nudge.workspaceId ?? null,
      userId,
      actorId: null,
      kind: 'nudge',
      entityType: 'nudge',
      entityId: null,
      dedupeKey: dedupeKeyFor(nudge, now),
      payload: JSON.stringify({ title: nudge.title, body: nudge.body, nudge: nudge.kind }),
    })
    .onConflictDoNothing({ target: [notifications.userId, notifications.dedupeKey] })
    .returning({ id: notifications.id });

  return inserted.length > 0;
}

/** Scan every user and deliver at most one nudge each. */
export async function scanNudges(db: Database, now: Date = new Date()): Promise<number> {
  const everyone = await db.select({ id: users.id }).from(users);

  let delivered = 0;

  for (const user of everyone) {
    const nudge = await nudgeFor(db, user.id);
    if (nudge && (await deliverNudge(db, user.id, nudge, now))) delivered++;
  }

  return delivered;
}
